# CONFIGURAÇÃO DO BANCO (XAMPP / MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/uc00605_cliente?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080